### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by bingo9062** [duoergun0729/2book#3]
运行book2的malware.py 
提示x=vectorizer.fit_transform(x)；TypeError: normalize() argument 2 must be unicode, not str
请问如何解决?

**Comment by daniel0720** [comment]
遇到了同样的问题，请问你解决了吗？

**Comment by bingo9062** [comment]
解决了，我好像把画图函数注释了，可能版本问题

**Comment by duoergun0729** [comment]
我把我环境给下  我这里同步最新代码都ok

**Comment by duoergun0729** [comment]
absl-py==0.7.1
astor==0.7.1
backports.functools-lru-cache==1.5
backports.lzma==0.0.13
backports.weakref==1.0.post1
boto==2.49.0
boto3==1.9.130
botocore==1.12.130
bz2file==0.98
certifi==2019.3.9
chardet==3.0.4
cycler==0.10.0
docutils==0.14
enum34==1.1.6
funcsigs==1.0.2
futures==3.2.0
gast==0.2.2
gensim==3.7.2
grpcio==1.19.0
h5py==2.9.0
hmmlearn==0.2.1
idna==2.8
jmespath==0.9.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.1
matplotlib==2.2.4
mock==2.0.0
numpy==1.16.2
pbr==5.1.3
Pillow==6.0.0
protobuf==3.7.1
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
requests==2.21.0
s3transfer==0.2.0
scikit-learn==0.20.3
scipy==1.2.1
six==1.12.0
sklearn==0.0
smart-open==1.8.1
subprocess32==3.5.3
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
tflearn==0.3.2
urllib3==1.24.1
Werkzeug==0.15.2
xgboost==0.82
